# Matemática para Ciencia de los Datos
# Trabajo Práctico 2

Profesor: Juan Luis Crespo Mariño, basado en trabajo previo de Luis Alexánder Calvo Valverde

Instituto Tecnológico de Costa Rica,

Programa Ciencia de Datos

---

Fecha de entrega: Jueves 29 de Octubre del 2024, a más tardar a las 6:00 pm.

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo jupyter ( .IPYNB ).

Estudiante(s):
1. Jonathan Chavarria
2. Felipe Quesada



---

**Pregunta 1**

Considerando que la transpuesta de una matriz es el resultado de cambiar las filas a columnas. Sea una matriz $A\in\mathbb{R}^{m\times n}$, su transpuesta se escribe como $A^{T}\in\mathbb{R}^{n\times m}$ y sus entradas están dadas por:

\begin{equation}
\left(A^{T}\right)_{i,j}=A_{j,i}.
\end{equation}

Proponga Usted dos matrices, $A\in\mathbb{R}^{4\times 3}$ y $B\in\mathbb{R}^{3\times 4}$ (no las busque en Internet, trate de proponer los valores por si mismo), y utilizando numpy muestre que las siguientes propiedades se cumplen con sus matrices propuestas.

**Note** que ni A ni B son cuadradas, y no tienen las mismas dimensiones.


**1.1 (15 puntos)**

- $\left(A^{T}\right)^{T}=A$


In [4]:
import numpy as np

A = np.array([[2 , 4 , 8] , [3, 6, 9] , [5, 10 ,15] , [7, 14 , 21]])
B = np.array([[ 2 , 3 , 5 , 7 ] , [ 11 , 13 , 17 , 19 ] , [ 23 , 29 , 31 , 37 ]])

def matrizTranspuesta (matriz):
    rows, cols = matriz.shape
    matrizTemporal = np.zeros((cols, rows))
    for i in range(cols):
        for j in range(rows):
            matrizTemporal[i][j] = matriz[j][i]
    return matrizTemporal

print("La matriz A es: \n" , A)
print("La matriz transpuesta de A es : \n" ,  matrizTranspuesta(A))
print("La matriz transpuesta de la matriz trasnpuesta de A es: \n" , matrizTranspuesta(matrizTranspuesta(A)))

print("La matriz B es: \n" ,  B)
print("La matriz transpuesta de B es: \n" ,  matrizTranspuesta(B))
print("La matriz transpuesta de la matriz trasnpuesta de B es: \n" , matrizTranspuesta(matrizTranspuesta(B)))

La matriz A es: 
 [[ 2  4  8]
 [ 3  6  9]
 [ 5 10 15]
 [ 7 14 21]]
La matriz transpuesta de A es : 
 [[ 2.  3.  5.  7.]
 [ 4.  6. 10. 14.]
 [ 8.  9. 15. 21.]]
La matriz transpuesta de la matriz trasnpuesta de A es: 
 [[ 2.  4.  8.]
 [ 3.  6.  9.]
 [ 5. 10. 15.]
 [ 7. 14. 21.]]
La matriz B es: 
 [[ 2  3  5  7]
 [11 13 17 19]
 [23 29 31 37]]
La matriz transpuesta de B es: 
 [[ 2. 11. 23.]
 [ 3. 13. 29.]
 [ 5. 17. 31.]
 [ 7. 19. 37.]]
La matriz transpuesta de la matriz trasnpuesta de B es: 
 [[ 2.  3.  5.  7.]
 [11. 13. 17. 19.]
 [23. 29. 31. 37.]]


**1.2 (15 puntos)**

- $\left(AB\right)^{T}=B^{T}A^{T}$


In [6]:
def multipMatrices ( A , B):
    matrizResultante = np.zeros((A.shape[0] , B.shape[1]))
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                matrizResultante[i][j] += A[i][k] * B[k][j]
    return matrizResultante
print(multipMatrices(A , B))

[[ 232.  290.  326.  386.]
 [ 279.  348.  396.  468.]
 [ 465.  580.  660.  780.]
 [ 651.  812.  924. 1092.]]


**1.3 (15 puntos)**

Para este ejercicio, **proponga dos matrices de igual dimensionalidad**


- $\left(A+B\right)^{T}=A^{T}+B^{T}$.


---

**Pregunta 2**


Un conjunto de vectores $\left\{ \vec{x}_{1},\vec{x}_{2},\ldots,\vec{x}_{n}\right\} \in\mathbb{R}^{m}$ se dice que es linealmente independiente, si ningún vector de tal conjunto puede ser representado como una combinación lineal del resto de vectores. De lo contrario, si uno de los vectores en tal conjunto puede ser representado como una combinación lineal del resto de vectores, entonces los vectores son linealmente dependientes, lo que se expresa como:

\begin{equation}
\vec{x}_{j}=\sum_{i=1}^{n-1}\alpha_{i}\vec{x}_{i}
\end{equation}

para cualquier conjunto de valores escalares $\alpha_{1},\ldots,\alpha_{n-1}\in\mathbb{R}$ se dice que el vector $\vec{x}_{j}\in\mathbb{R}^{m}$ es linealmente dependiente de los vectores $\vec{x}_{i}$.


**2.1 (15 puntos)**

Proponga una matriz $A\in\mathbb{R}^{4\times 3}$, cuyos vectores columnas sean linealmente independientes, calcule su rango para mostrar que es de rango $3$ (puede utilizar matrix_rank).


**2.2 (15 puntos)**

Ahora haga los cambios necesarios a su matriz de manera que pase a rango $2$.

---

**Pregunta 3 (25 puntos)**

Utilizando el archivo "Dataset_usar.csv", haga:
- Cargue el archivo.
- Utilizando el modelo $Ax=b$
    - Conforme la matriz $A$ con las primeras 8 columnas.
    - Conforme el vector $b$ con la última columna de la derecha.
    - Calcule el vector de pesos ($x$), del tipo $A^{-1}b=x$
    - Calcule un b_estimado con $A$ e $x$
    - Calcule la norma 2 de la diferencia entre b y b_estimado.
    - Grafique b y b_estimado.

